use std::net::SocketAddr;
use std::path::PathBuf;

use anyhow::{Context, Result, bail};
use clap::{Args, Parser, Subcommand};

use crate::config::LoadedConfig;
use crate::counter_api;
use crate::doctor;
use crate::guest;
use crate::launcher;

#[derive(Debug, Parser)]
#[command(author, version, about)]
pub struct Cli {
    /// Optional TOML config file. If omitted, minivm will auto-load ./minivm.toml
    /// when present and otherwise fall back to built-in defaults.
    #[arg(long, global = true)]
    config: Option<PathBuf>,

    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Run the host-side API that increments a shared counter.
    Serve(ServeArgs),
    /// Build a tiny initramfs containing BusyBox plus the guest /init script.
    BuildInitramfs(BuildInitramfsArgs),
    /// Launch N TAP-backed QEMU guests that will call the host API.
    Launch(LaunchArgs),
    /// Validate the host environment and loaded configuration.
    Doctor(DoctorArgs),
    /// Print the default guest init script to stdout for inspection.
    PrintGuestInit,
}

#[derive(Debug, Clone, Args)]
pub struct ServeArgs {
    /// Address that the counter API should bind to. This should normally be the
    /// bridge address that guests can reach.
    #[arg(long)]
    pub listen: Option<SocketAddr>,
}

#[derive(Debug, Clone, Args)]
pub struct BuildInitramfsArgs {
    /// Path to a static BusyBox binary. This binary is copied into /bin/busybox
    /// inside the generated initramfs.
    #[arg(long)]
    pub busybox: Option<PathBuf>,

    /// Path to write the generated initramfs archive to.
    #[arg(long)]
    pub output: Option<PathBuf>,

    /// Optional path to a custom init script. When omitted we embed guest/init.
    #[arg(long)]
    pub init_script: Option<PathBuf>,
}

#[derive(Debug, Clone, Args)]
pub struct LaunchArgs {
    /// Number of guests to boot.
    #[arg(long)]
    pub count: Option<usize>,

    /// Linux kernel image to boot. A bzImage that already includes virtio-net
    /// support is the simplest option for this prototype.
    #[arg(long)]
    pub kernel: Option<PathBuf>,

    /// Initramfs generated by the build-initramfs subcommand.
    #[arg(long)]
    pub initramfs: Option<PathBuf>,

    /// Directory for serial logs and other runtime artifacts.
    #[arg(long)]
    pub workdir: Option<PathBuf>,

    /// Host API URL that the guest /init script will call.
    #[arg(long)]
    pub host_api: Option<String>,

    /// Bridge that the TAP devices will be attached to.
    #[arg(long)]
    pub bridge: Option<String>,

    /// IPv4 subnet base. The host is assigned .1 and guests start at .2.
    #[arg(long)]
    pub subnet_base: Option<std::net::Ipv4Addr>,

    /// Prefix length for the guest subnet.
    #[arg(long)]
    pub prefix_len: Option<u8>,

    /// RAM size per guest.
    #[arg(long)]
    pub memory_mib: Option<u32>,

    /// Hypervisor backend. Only `qemu` is currently implemented.
    #[arg(long)]
    pub backend: Option<String>,

    /// QEMU executable to invoke.
    #[arg(long)]
    pub qemu_bin: Option<String>,

    /// QEMU machine type. `microvm` is the best default when available.
    #[arg(long)]
    pub machine: Option<String>,

    /// QEMU acceleration mode. Use `kvm` on Linux; `tcg` is useful for
    /// debugging in environments without KVM.
    #[arg(long)]
    pub accel: Option<String>,

    /// Prefix for TAP device names. Linux limits interface names to 15 chars.
    #[arg(long)]
    pub tap_prefix: Option<String>,

    /// Skip TAP creation and assume the named TAP devices already exist.
    #[arg(long, default_value_t = false)]
    pub skip_tap_setup: bool,

    /// Keep TAP devices around after the guests exit. The default behavior is
    /// to clean them up automatically.
    #[arg(long, default_value_t = false)]
    pub keep_taps: bool,
}

#[derive(Debug, Clone, Args)]
pub struct DoctorArgs {
    /// Exit non-zero if any hard check fails.
    #[arg(long, default_value_t = false)]
    pub strict: bool,
}

pub async fn run() -> Result<()> {
    let cli = Cli::parse();
    let loaded_config = crate::config::load(cli.config.as_deref())?;

    match cli.command {
        Command::Serve(args) => counter_api::serve(resolve_serve(args, &loaded_config)?).await,
        Command::BuildInitramfs(args) => {
            guest::build_initramfs(resolve_build_initramfs(args, &loaded_config)?).await
        }
        Command::Launch(args) => launcher::launch(resolve_launch(args, &loaded_config)?).await,
        Command::Doctor(args) => doctor::run(doctor::DoctorConfig {
            strict: args.strict,
            loaded_config,
        }),
        Command::PrintGuestInit => {
            print!("{}", guest::default_init_script());
            Ok(())
        }
    }
}

fn resolve_serve(args: ServeArgs, loaded: &LoadedConfig) -> Result<counter_api::ServeConfig> {
    Ok(counter_api::ServeConfig {
        listen: args
            .listen
            .or(loaded.data.serve.listen)
            .unwrap_or_else(|| "127.0.0.1:8080".parse().expect("valid default socket addr")),
    })
}

fn resolve_build_initramfs(
    args: BuildInitramfsArgs,
    loaded: &LoadedConfig,
) -> Result<guest::BuildInitramfsConfig> {
    let busybox = args
        .busybox
        .or_else(|| loaded.data.build.busybox.clone())
        .context("busybox is required; pass --busybox or set [build].busybox in minivm.toml")?;

    let output = args
        .output
        .or_else(|| loaded.data.build.output.clone())
        .unwrap_or_else(|| PathBuf::from("out/initramfs.cpio"));

    let init_script = args
        .init_script
        .or_else(|| loaded.data.build.init_script.clone());

    Ok(guest::BuildInitramfsConfig {
        busybox,
        output,
        init_script,
    })
}

fn resolve_launch(args: LaunchArgs, loaded: &LoadedConfig) -> Result<launcher::LaunchConfig> {
    let file = &loaded.data.launch;

    let backend = args
        .backend
        .or_else(|| file.backend.clone())
        .unwrap_or_else(|| "qemu".to_owned());

    let count = args.count.or(file.count).unwrap_or(1);
    if count == 0 {
        bail!("--count must be at least 1");
    }

    let kernel = args
        .kernel
        .or_else(|| file.kernel.clone())
        .context("kernel is required; pass --kernel or set [launch].kernel in minivm.toml")?;

    let initramfs = args
        .initramfs
        .or_else(|| file.initramfs.clone())
        .or_else(|| loaded.data.build.output.clone())
        .context(
            "initramfs is required; pass --initramfs or set [build].output / [launch].initramfs in minivm.toml",
        )?;

    Ok(launcher::LaunchConfig {
        count,
        kernel,
        initramfs,
        workdir: args
            .workdir
            .or_else(|| file.workdir.clone())
            .unwrap_or_else(|| PathBuf::from("runtime")),
        host_api: args
            .host_api
            .or_else(|| file.host_api.clone())
            .unwrap_or_else(|| "http://192.168.100.1:8080/incr".to_owned()),
        bridge: args
            .bridge
            .or_else(|| file.bridge.clone())
            .unwrap_or_else(|| "minivm0".to_owned()),
        subnet_base: args
            .subnet_base
            .or(file.subnet_base)
            .unwrap_or_else(|| "192.168.100.0".parse().expect("valid default subnet")),
        prefix_len: args.prefix_len.or(file.prefix_len).unwrap_or(24),
        memory_mib: args.memory_mib.or(file.memory_mib).unwrap_or(128),
        backend,
        qemu_bin: args
            .qemu_bin
            .or_else(|| file.qemu_bin.clone())
            .unwrap_or_else(|| "qemu-system-x86_64".to_owned()),
        machine: args
            .machine
            .or_else(|| file.machine.clone())
            .unwrap_or_else(|| "microvm".to_owned()),
        accel: args
            .accel
            .or_else(|| file.accel.clone())
            .unwrap_or_else(|| "kvm".to_owned()),
        tap_prefix: args
            .tap_prefix
            .or_else(|| file.tap_prefix.clone())
            .unwrap_or_else(|| "mvm".to_owned()),
        skip_tap_setup: args.skip_tap_setup || file.skip_tap_setup.unwrap_or(false),
        keep_taps: args.keep_taps || file.keep_taps.unwrap_or(false),
    })
}
