use std::net::SocketAddr;
use std::path::PathBuf;

use anyhow::Result;
use clap::{Args, Parser, Subcommand};

use crate::counter_api;
use crate::guest;
use crate::launcher;

#[derive(Debug, Parser)]
#[command(author, version, about)]
pub struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Run the host-side API that increments a shared counter.
    Serve(ServeArgs),
    /// Build a tiny initramfs containing BusyBox plus the guest /init script.
    BuildInitramfs(BuildInitramfsArgs),
    /// Launch N TAP-backed QEMU guests that will call the host API.
    Launch(LaunchArgs),
    /// Print the default guest init script to stdout for inspection.
    PrintGuestInit,
}

#[derive(Debug, Clone, Args)]
pub struct ServeArgs {
    /// Address that the counter API should bind to. This should normally be the
    /// bridge address that guests can reach.
    #[arg(long, default_value = "127.0.0.1:8080")]
    pub listen: SocketAddr,
}

#[derive(Debug, Clone, Args)]
pub struct BuildInitramfsArgs {
    /// Path to a static BusyBox binary. This binary is copied into /bin/busybox
    /// inside the generated initramfs.
    #[arg(long)]
    pub busybox: PathBuf,

    /// Path to write the generated initramfs archive to.
    #[arg(long)]
    pub output: PathBuf,

    /// Optional path to a custom init script. When omitted we embed guest/init.
    #[arg(long)]
    pub init_script: Option<PathBuf>,
}

#[derive(Debug, Clone, Args)]
pub struct LaunchArgs {
    /// Number of guests to boot.
    #[arg(long)]
    pub count: usize,

    /// Linux kernel image to boot. A bzImage that already includes virtio-net
    /// support is the simplest option for this prototype.
    #[arg(long)]
    pub kernel: PathBuf,

    /// Initramfs generated by the build-initramfs subcommand.
    #[arg(long)]
    pub initramfs: PathBuf,

    /// Directory for serial logs and other runtime artifacts.
    #[arg(long, default_value = "runtime")]
    pub workdir: PathBuf,

    /// Host API URL that the guest /init script will call.
    #[arg(long, default_value = "http://192.168.100.1:8080/incr")]
    pub host_api: String,

    /// Bridge that the TAP devices will be attached to.
    #[arg(long, default_value = "minivm0")]
    pub bridge: String,

    /// IPv4 subnet base. The host is assigned .1 and guests start at .2.
    #[arg(long, default_value = "192.168.100.0")]
    pub subnet_base: String,

    /// Prefix length for the guest subnet.
    #[arg(long, default_value_t = 24)]
    pub prefix_len: u8,

    /// RAM size per guest.
    #[arg(long, default_value_t = 128)]
    pub memory_mib: u32,

    /// QEMU executable to invoke.
    #[arg(long, default_value = "qemu-system-x86_64")]
    pub qemu_bin: String,

    /// QEMU machine type. `microvm` is the best default when available.
    #[arg(long, default_value = "microvm")]
    pub machine: String,

    /// QEMU acceleration mode. Use `kvm` on Linux; `tcg` is useful for
    /// debugging in environments without KVM.
    #[arg(long, default_value = "kvm")]
    pub accel: String,

    /// Prefix for TAP device names. Linux limits interface names to 15 chars.
    #[arg(long, default_value = "mvm")]
    pub tap_prefix: String,

    /// Skip TAP creation and assume the named TAP devices already exist.
    #[arg(long, default_value_t = false)]
    pub skip_tap_setup: bool,

    /// Keep TAP devices around after the guests exit. The default behavior is
    /// to clean them up automatically.
    #[arg(long, default_value_t = false)]
    pub keep_taps: bool,
}

pub async fn run() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Serve(args) => counter_api::serve(args).await,
        Command::BuildInitramfs(args) => guest::build_initramfs(args).await,
        Command::Launch(args) => launcher::launch(args).await,
        Command::PrintGuestInit => {
            print!("{}", guest::default_init_script());
            Ok(())
        }
    }
}
